package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineCategory;
import com.lumchine.db.domain.LumchineCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    long countByExample(LumchineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int insert(LumchineCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int insertSelective(LumchineCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    LumchineCategory selectOneByExample(LumchineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    LumchineCategory selectOneByExampleSelective(@Param("example") LumchineCategoryExample example, @Param("selective") LumchineCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    List<LumchineCategory> selectByExampleSelective(@Param("example") LumchineCategoryExample example, @Param("selective") LumchineCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    List<LumchineCategory> selectByExample(LumchineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    LumchineCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    LumchineCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    LumchineCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineCategory record, @Param("example") LumchineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineCategory record, @Param("example") LumchineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}