package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineCart;
import com.lumchine.db.domain.LumchineCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    long countByExample(LumchineCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int insert(LumchineCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int insertSelective(LumchineCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    LumchineCart selectOneByExample(LumchineCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    LumchineCart selectOneByExampleSelective(@Param("example") LumchineCartExample example, @Param("selective") LumchineCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    List<LumchineCart> selectByExampleSelective(@Param("example") LumchineCartExample example, @Param("selective") LumchineCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    List<LumchineCart> selectByExample(LumchineCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    LumchineCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    LumchineCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    LumchineCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineCart record, @Param("example") LumchineCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineCart record, @Param("example") LumchineCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}