package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineFeedback;
import com.lumchine.db.domain.LumchineFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    long countByExample(LumchineFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int insert(LumchineFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int insertSelective(LumchineFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    LumchineFeedback selectOneByExample(LumchineFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    LumchineFeedback selectOneByExampleSelective(@Param("example") LumchineFeedbackExample example, @Param("selective") LumchineFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    List<LumchineFeedback> selectByExampleSelective(@Param("example") LumchineFeedbackExample example, @Param("selective") LumchineFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    List<LumchineFeedback> selectByExample(LumchineFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    LumchineFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    LumchineFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    LumchineFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineFeedback record, @Param("example") LumchineFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineFeedback record, @Param("example") LumchineFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}