package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineAd;
import com.lumchine.db.domain.LumchineAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    long countByExample(LumchineAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int insert(LumchineAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int insertSelective(LumchineAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    LumchineAd selectOneByExample(LumchineAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    LumchineAd selectOneByExampleSelective(@Param("example") LumchineAdExample example, @Param("selective") LumchineAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    List<LumchineAd> selectByExampleSelective(@Param("example") LumchineAdExample example, @Param("selective") LumchineAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    List<LumchineAd> selectByExample(LumchineAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    LumchineAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    LumchineAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    LumchineAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineAd record, @Param("example") LumchineAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineAd record, @Param("example") LumchineAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}