package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineUserFormid;
import com.lumchine.db.domain.LumchineUserFormidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    long countByExample(LumchineUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int insert(LumchineUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(LumchineUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    LumchineUserFormid selectOneByExample(LumchineUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    LumchineUserFormid selectOneByExampleSelective(@Param("example") LumchineUserFormidExample example, @Param("selective") LumchineUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    List<LumchineUserFormid> selectByExampleSelective(@Param("example") LumchineUserFormidExample example, @Param("selective") LumchineUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    List<LumchineUserFormid> selectByExample(LumchineUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    LumchineUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    LumchineUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    LumchineUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineUserFormid record, @Param("example") LumchineUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineUserFormid record, @Param("example") LumchineUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}