package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineCoupon;
import com.lumchine.db.domain.LumchineCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    long countByExample(LumchineCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int insert(LumchineCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int insertSelective(LumchineCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    LumchineCoupon selectOneByExample(LumchineCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    LumchineCoupon selectOneByExampleSelective(@Param("example") LumchineCouponExample example, @Param("selective") LumchineCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    List<LumchineCoupon> selectByExampleSelective(@Param("example") LumchineCouponExample example, @Param("selective") LumchineCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    List<LumchineCoupon> selectByExample(LumchineCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    LumchineCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    LumchineCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    LumchineCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineCoupon record, @Param("example") LumchineCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineCoupon record, @Param("example") LumchineCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}