package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineRole;
import com.lumchine.db.domain.LumchineRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    long countByExample(LumchineRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int insert(LumchineRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int insertSelective(LumchineRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    LumchineRole selectOneByExample(LumchineRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    LumchineRole selectOneByExampleSelective(@Param("example") LumchineRoleExample example, @Param("selective") LumchineRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    List<LumchineRole> selectByExampleSelective(@Param("example") LumchineRoleExample example, @Param("selective") LumchineRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    List<LumchineRole> selectByExample(LumchineRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    LumchineRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    LumchineRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    LumchineRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineRole record, @Param("example") LumchineRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineRole record, @Param("example") LumchineRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}