package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineGrouponRules;
import com.lumchine.db.domain.LumchineGrouponRulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(LumchineGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int insert(LumchineGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(LumchineGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    LumchineGrouponRules selectOneByExample(LumchineGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    LumchineGrouponRules selectOneByExampleSelective(@Param("example") LumchineGrouponRulesExample example, @Param("selective") LumchineGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    List<LumchineGrouponRules> selectByExampleSelective(@Param("example") LumchineGrouponRulesExample example, @Param("selective") LumchineGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    List<LumchineGrouponRules> selectByExample(LumchineGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    LumchineGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    LumchineGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    LumchineGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineGrouponRules record, @Param("example") LumchineGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineGrouponRules record, @Param("example") LumchineGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}