package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineFootprint;
import com.lumchine.db.domain.LumchineFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    long countByExample(LumchineFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int insert(LumchineFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int insertSelective(LumchineFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    LumchineFootprint selectOneByExample(LumchineFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    LumchineFootprint selectOneByExampleSelective(@Param("example") LumchineFootprintExample example, @Param("selective") LumchineFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    List<LumchineFootprint> selectByExampleSelective(@Param("example") LumchineFootprintExample example, @Param("selective") LumchineFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    List<LumchineFootprint> selectByExample(LumchineFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    LumchineFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    LumchineFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    LumchineFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineFootprint record, @Param("example") LumchineFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineFootprint record, @Param("example") LumchineFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}