package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineGoodsAttribute;
import com.lumchine.db.domain.LumchineGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(LumchineGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int insert(LumchineGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(LumchineGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    LumchineGoodsAttribute selectOneByExample(LumchineGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    LumchineGoodsAttribute selectOneByExampleSelective(@Param("example") LumchineGoodsAttributeExample example, @Param("selective") LumchineGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    List<LumchineGoodsAttribute> selectByExampleSelective(@Param("example") LumchineGoodsAttributeExample example, @Param("selective") LumchineGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    List<LumchineGoodsAttribute> selectByExample(LumchineGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    LumchineGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    LumchineGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    LumchineGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineGoodsAttribute record, @Param("example") LumchineGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineGoodsAttribute record, @Param("example") LumchineGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}