package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineBrand;
import com.lumchine.db.domain.LumchineBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    long countByExample(LumchineBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int insert(LumchineBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int insertSelective(LumchineBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    LumchineBrand selectOneByExample(LumchineBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    LumchineBrand selectOneByExampleSelective(@Param("example") LumchineBrandExample example, @Param("selective") LumchineBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    List<LumchineBrand> selectByExampleSelective(@Param("example") LumchineBrandExample example, @Param("selective") LumchineBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    List<LumchineBrand> selectByExample(LumchineBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    LumchineBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    LumchineBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    LumchineBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineBrand record, @Param("example") LumchineBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineBrand record, @Param("example") LumchineBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}