package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineSystem;
import com.lumchine.db.domain.LumchineSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    long countByExample(LumchineSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int insert(LumchineSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int insertSelective(LumchineSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    LumchineSystem selectOneByExample(LumchineSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    LumchineSystem selectOneByExampleSelective(@Param("example") LumchineSystemExample example, @Param("selective") LumchineSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    List<LumchineSystem> selectByExampleSelective(@Param("example") LumchineSystemExample example, @Param("selective") LumchineSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    List<LumchineSystem> selectByExample(LumchineSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    LumchineSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    LumchineSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    LumchineSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineSystem record, @Param("example") LumchineSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineSystem record, @Param("example") LumchineSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}