package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineComment;
import com.lumchine.db.domain.LumchineCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    long countByExample(LumchineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int insert(LumchineComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int insertSelective(LumchineComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    LumchineComment selectOneByExample(LumchineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    LumchineComment selectOneByExampleSelective(@Param("example") LumchineCommentExample example, @Param("selective") LumchineComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    List<LumchineComment> selectByExampleSelective(@Param("example") LumchineCommentExample example, @Param("selective") LumchineComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    List<LumchineComment> selectByExample(LumchineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    LumchineComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    LumchineComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    LumchineComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineComment record, @Param("example") LumchineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineComment record, @Param("example") LumchineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}