package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineCollect;
import com.lumchine.db.domain.LumchineCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    long countByExample(LumchineCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int insert(LumchineCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int insertSelective(LumchineCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    LumchineCollect selectOneByExample(LumchineCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    LumchineCollect selectOneByExampleSelective(@Param("example") LumchineCollectExample example, @Param("selective") LumchineCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    List<LumchineCollect> selectByExampleSelective(@Param("example") LumchineCollectExample example, @Param("selective") LumchineCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    List<LumchineCollect> selectByExample(LumchineCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    LumchineCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    LumchineCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    LumchineCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineCollect record, @Param("example") LumchineCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineCollect record, @Param("example") LumchineCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}