package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineSearchHistory;
import com.lumchine.db.domain.LumchineSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    long countByExample(LumchineSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int insert(LumchineSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int insertSelective(LumchineSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    LumchineSearchHistory selectOneByExample(LumchineSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    LumchineSearchHistory selectOneByExampleSelective(@Param("example") LumchineSearchHistoryExample example, @Param("selective") LumchineSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    List<LumchineSearchHistory> selectByExampleSelective(@Param("example") LumchineSearchHistoryExample example, @Param("selective") LumchineSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    List<LumchineSearchHistory> selectByExample(LumchineSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    LumchineSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    LumchineSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    LumchineSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineSearchHistory record, @Param("example") LumchineSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineSearchHistory record, @Param("example") LumchineSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}