package com.lumchine.db.dao;

import com.lumchine.db.domain.LumchineGoodsProduct;
import com.lumchine.db.domain.LumchineGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LumchineGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    long countByExample(LumchineGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(LumchineGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int insert(LumchineGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(LumchineGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    LumchineGoodsProduct selectOneByExample(LumchineGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    LumchineGoodsProduct selectOneByExampleSelective(@Param("example") LumchineGoodsProductExample example, @Param("selective") LumchineGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    List<LumchineGoodsProduct> selectByExampleSelective(@Param("example") LumchineGoodsProductExample example, @Param("selective") LumchineGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    List<LumchineGoodsProduct> selectByExample(LumchineGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    LumchineGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LumchineGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    LumchineGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    LumchineGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LumchineGoodsProduct record, @Param("example") LumchineGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LumchineGoodsProduct record, @Param("example") LumchineGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LumchineGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LumchineGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LumchineGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lumchine_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}